// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jklsjujvrqfwdambxczg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbHNqdWp2cnFmd2RhbWJ4Y3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNTA5MzAsImV4cCI6MjA1NTkyNjkzMH0.-byE4wKxQUFnFTwxYQvs5S-khC4_h9vroe9JtKoQTuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);